# 12.1 TensorFlow快速浏览

# 12.2 像 NumPy 一样使用 TensorFlow

## 12.2.1 张量和操作

In [1]:
import tensorflow as tf

张量通常是一个多维数组，但也可以保存标量。

In [2]:
# 创建张量
tf.constant([[1., 2., 3.], [4., 5., 6.]])   # matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [5]:
t.dtype

tf.float32

In [6]:
# 索引的工作方式类似于NumPy:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [7]:
# 如果t是二维数组，t[...,1]等价于t[:,1]；如果是三维数值，t[...,1]等价于t[:,:,1]
# tf.newaxis和np.newaxis功能相同，都是增加维度
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

张量操作

In [9]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [11]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## 12.2.2 张量和 NumPy

In [12]:
import numpy as np

a = np.array([2., 4., 5.])

In [13]:
# 创建常量
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [14]:
t.numpy()   # or np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [15]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [16]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

NumPy使用64位精度，而Tensorflow使用32位精度。  
32位精度通常对于神经网络来说绰绰有余。  
当从NumPy数组创建张量时，确保设置dtype = tf.float32.

## 12.2.3 类型转换

Tensorflow不会自动执行任何类型转换

In [17]:
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [18]:
# 需要类型转换，使用tf.cast()
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## 12.2.4 变量

In [19]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

## 12.2.5 其他数据结构

* *稀疏张量 (tf.SparseTensor)*
* *张量数组 (tf.TensorArray)*
* *不规则张量 (tf.RaggedTensor)*
* *字符串张量*
* *集合*
* *队列*